### ISSUE TITLE
罗刹

### ISSUE THREAD

**Issue by Chen-2905** [starrail-tech/srEngineBugReport#4]
行迹治疗
请把下面这一行删了！！
![image](https://github.com/starrail-tech/srEngineBugReport/assets/108560346/9c72a61c-780c-460e-ace8-025d897a6436)

**Comment by Chen-2905** [comment]
罗刹结界治疗在日志里显示混乱
![FSFBIE`3O~RK~4@B(RJW~EL](https://github.com/starrail-tech/srEngineBugReport/assets/108560346/07fab55f-156e-420d-8c43-2396298984a7)
看不到对攻击发起者的回血记录，且本回合应当回的血延迟到下回合的日志里了

![)IQ58583O~YLV)){U79KH3](https://github.com/starrail-tech/srEngineBugReport/assets/108560346/a59a36f1-f48b-41b8-8719-2bad8ebf9db1)
![QEYK32(P F BXG(~86S$OPD](https://github.com/starrail-tech/srEngineBugReport/assets/108560346/5f3932f4-3bef-4ffc-ba00-8722f3dacd8a)
为什么刃造成伤害之后，群体回血在下一回合的日志里
![P1W$%KSA081_GLUL9`T(~YA](https://github.com/starrail-tech/srEngineBugReport/assets/108560346/fe53898f-9885-42ba-a350-ce9886339a72)
![%PF6W98`P@XMMF4P{7UB9{P](https://github.com/starrail-tech/srEngineBugReport/assets/108560346/1adbdce7-8cd5-4108-a041-9eaed3f601bb)

**Comment by Chen-2905** [comment]
额外天赋 回血判定次数有误
“啊 懂了 你上面3个怪 每个怪受到了3次BEATTACKED事件”

**Comment by LisannaRin** [comment]
fixed
