### ISSUE TITLE
刃

### ISSUE THREAD

**Issue by Chen-2905** [starrail-tech/srEngineBugReport#5]
![N3}C9BNL_NU6{PB8HY OKYT](https://github.com/starrail-tech/srEngineBugReport/assets/108560346/1cceac4f-13d6-4038-883f-80c5eb828b8d)
首先这俩方框的结算顺序反了，普攻的多段伤害结算都在追加攻击天赋之前
其次停云的赐福每次行动只结算一次，并不是每段结算一次

**Comment by Chen-2905** [comment]
e回合后无法插入布洛尼亚终结技，模拟器直接卡住不能动了

古月浪子 10:28 发送
回合有优先级吧，普通回合是1，青雀的额外回合是2，终结技是3，希儿再现的额外回合也是3

**Comment by Chen-2905** [comment]
刃的强普是2单位削韧

**Comment by LisannaRin** [comment]
顺序还没修，其他修了
