### ISSUE TITLE
怪物轮次

### ISSUE THREAD

**Issue by Chen-2905** [starrail-tech/srEngineBugReport#6]
怪物转场
![Q1T_G@P%7ECYS ~F7ZY 0W1](https://github.com/starrail-tech/srEngineBugReport/assets/108560346/2552f073-0810-454e-b4ca-c869b1dee433)
血负了怪不消失不转场，这个bug最早在卡芙卡上架模拟器就有了
![$)M@9T2ZE1RH`10G42DQ0(G](https://github.com/starrail-tech/srEngineBugReport/assets/108560346/fdc24e11-8e10-4e65-abd1-174dd97c810c)
要板鸭拉一下才转场（一个新回合），但如果此时是攻击型角色，就亏一回合伤害了

**Comment by LisannaRin** [comment]
fixed
