### ISSUE TITLE
战斗进行不下去

### ISSUE THREAD

**Issue by Chen-2905** [starrail-tech/srEngineBugReport#8]
![image](https://github.com/starrail-tech/srEngineBugReport/assets/108560346/af243bbb-fa3e-47d0-b9a3-592ce02b2f46)
每次到第16轮，鸭鸭e的时候都会卡主不能动

**Comment by Chen-2905** [comment]
刷新重新加载就这样了
![image](https://github.com/starrail-tech/srEngineBugReport/assets/108560346/273d61b4-7779-493a-b312-f32ceab7bbe3)

**Comment by LisannaRin** [comment]
fixed 大概
